#!/bin/bash
rm summary.output
for STOCK in UPW XTN RYU VPU IDU PUI XLU FXU JXI DBU XHS AXHE FXH CURE RXL HGEM PJP VHT IHE IBB PXE UGA PXI MLPL BNO CGW AMJ AMLP RYE DIG URTH VNQI ACCU BJK TZW CARZ RXI AADR IGEM COLX EEMS EMFN GMFS ECON FEM EWEF EEMV EELV PCY EMB KBWB KBWI KBWC CSD UGE PEJ KBWY RTL XRT UCC EWMD RETL KBWP EWSM PXLV FNK FPX VONV PSCM VOOV EDEN EWGS EWSS AXSL EWUS ENZL DBJP EWHS EPHE DBEF PALL SPGH UGL SLV DBS SGOL GLD DGP DBP DUST UJB TYD ZIV HYMB IBND XMPT HYD HYLD HYS MLN
do
  echo Analyzing $STOCK...
  ./test_stock.sh $STOCK
done
